name: den_d
description: "SvatebnÃ­ plÃ¡novaÄ â€“ aplikace pro organizaci vaÅ¡eho velkÃ©ho dne."
publish_to: 'none' # OdstraÅˆte, pokud chcete publikovat na pub.dev

version: 1.3.4+36

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  table_calendar: ^3.2.0
  intl: 0.20.2  # Je potÅ™eba kvÅ¯li flutter_localizations, kterÃ¡ je zafixovanÃ¡ na tuto verzi
  timezone: ^0.10.1
  percent_indicator: ^4.2.5
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  in_app_purchase: ^3.2.3
  in_app_purchase_android: 0.4.0+5
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0
  get_it: ^8.2.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  logger: ^2.6.1
  easy_localization: ^3.0.8
  http: ^1.4.0
  fl_chart: ^1.0.0
  flutter_local_notifications: ^19.4.0  # Ponechejte novÄ›jÅ¡Ã­ verzi
  pdf: ^3.11.3
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  google_fonts: ^6.3.0
  open_file: ^3.5.10
  connectivity_plus: ^6.1.4
  firebase_performance: ^0.11.0
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  mockito: ^5.5.0
  permission_handler: ^12.0.1
  pointycastle: ^4.0.0
  url_launcher: ^6.3.2
  flutter_markdown: ^0.7.7+1
  app_links: ^6.4.1
  firebase_app_check: ^0.4.1
  firebase_messaging: ^16.0.2
  build_runner: ^2.10.1
  app_tracking_transparency: ^2.0.6+1

fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
      - asset: assets/fonts/Roboto-Bold.ttf
        weight: 700

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.11
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1


flutter:
  uses-material-design: true

  assets:
    - assets/config.json
    - assets/images/logo.png
    - assets/translations/cs.json
    - assets/translations/en.json
    - assets/translations/es.json
    - assets/translations/pl.json
    - assets/translations/fr.json
    - assets/translations/de.json
    - assets/translations/uk.json
    - assets/config/
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/chatbot.png
    - assets/fonts/Roboto-Regular.ttf    # â† PÅ˜IDEJ TENTO Å˜ÃDEK
    - assets/fonts/Roboto-Bold.ttf
   # PrÃ¡vnÃ­ dokumenty - ÄŒESKY
    - assets/legal/cs/privacy_policy.md
    - assets/legal/cs/terms_of_service.md

    # PrÃ¡vnÃ­ dokumenty - ANGLICKY
    - assets/legal/en/privacy_policy.md
    - assets/legal/en/terms_of_service.md

    # PrÃ¡vnÃ­ dokumenty - NÄšMECKY
    - assets/legal/de/privacy_policy.md
    - assets/legal/de/terms_of_service.md

    # PrÃ¡vnÃ­ dokumenty - Å PANÄšLSKY
    - assets/legal/es/privacy_policy.md
    - assets/legal/es/terms_of_service.md

    # PrÃ¡vnÃ­ dokumenty - FRANCOUZSKY
    - assets/legal/fr/privacy_policy.md
    - assets/legal/fr/terms_of_service.md

    # PrÃ¡vnÃ­ dokumenty - POLSKY
    - assets/legal/pl/privacy_policy.md
    - assets/legal/pl/terms_of_service.md

    # PrÃ¡vnÃ­ dokumenty - UKRAJINSKY
    - assets/legal/uk/privacy_policy.md
    - assets/legal/uk/terms_of_service.md

# ðŸŸ¢ AutomatizovanÃ© vizuÃ¡ly pro iOS i Android

flutter_launcher_name:
  name: "Den D"

flutter_launcher_icons:
  ios: true
  android: true
  image_path: assets/images/logo.png   # zde mÅ¯Å¾eÅ¡ dÃ¡t jinÃ© logo pro ikonu
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  ios: true
  android: true
  android_12:
    color: "#FFFFFF"
